name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-logs:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    # env:
    #   SECRET_MONGODB_CONNECTION: ${{ secrets.SECRET_MONGODB_CONNECTION }}
    #   SECRET_JWT_KEY: ${{ secrets.SECRET_JWT_KEY }}
    #   SECRET_EMAIL_PASSWORD: ${{ secrets.SECRET_EMAIL_PASSWORD }}
    #   SECRET_COOKIE_SECURE_SETTING: ${{ secrets.SECRET_COOKIE_SECURE_SETTING }}
    #   SECRET_INTERNAL_API_KEY: ${{ secrets.SECRET_INTERNAL_API_KEY }}
    #   SECRET_VALID_AUTH_TOKEN: ${{ secrets.SECRET_VALID_AUTH_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: |
          npm i

      #   - name: Test Jest API
      #     run: |
      #       npm run test:unit

      - name: Test Playwright API
        run: |
          npx playwright install --with-deps chromium
          npx playwright test --project="Google Chrome"

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
